# Generated by Django 4.2.6 on 2023-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_tag_order_book_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Historical Fiction', 'Historical Fiction'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
