# Generated by Django 4.2.6 on 2023-10-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_remove_order_tag_alter_book_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='addres',
            new_name='address',
        ),
    ]
