# Generated by Django 4.2.6 on 2023-11-02 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0006_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
