# Generated by Django 4.2.6 on 2023-11-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='user_img.png', null=True, upload_to='profile_images'),
        ),
    ]
