# Generated by Django 4.2.6 on 2023-11-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_alter_person_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
    ]
