# Generated by Django 4.2.6 on 2023-11-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
