# Generated by Django 4.2.6 on 2023-11-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='user_img.png', upload_to='profile_images'),
        ),
    ]
