# Generated by Django 4.2.6 on 2023-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_alter_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
