# Generated by Django 4.2.7 on 2023-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_alter_person_address_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
