# Generated by Django 4.2.7 on 2023-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0021_alter_person_address_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
