# Generated by Django 4.2.7 on 2023-11-13 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0024_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='person',
            new_name='customer',
        ),
    ]
